const AboutPage = () => {
    return (
      <>
      <div className="col-6 offset-3 rounded bg-dark text-light p-3 mt-2">
        <h3>AboutPage</h3>
        <hr />
        <p><span>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis voluptas esse error quibusdam! Officiis quis deserunt, incidunt similique alias quaerat temporibus hic iste adipisci aliquid, iure, blanditiis nisi est voluptatem.</span><span>Expedita repudiandae, iste quod dolor commodi enim maiores? Est inventore doloribus earum alias consequatur exercitationem, repudiandae laudantium iste libero, accusantium similique quod consectetur modi voluptatem illum odit culpa quidem labore.</span><span>Tempora consequatur blanditiis harum alias. Eos culpa natus quos quod, alias atque, fuga cumque velit vitae non omnis, nisi saepe dignissimos ipsa ut quae nulla sunt similique ex distinctio ea!</span><span>Sint dolore enim consectetur ex, nihil sapiente eius ad a. Fugiat molestiae modi accusamus officiis fuga suscipit rem perferendis maiores beatae distinctio. Reprehenderit repellendus, velit beatae amet quibusdam voluptates deleniti.</span><span>Enim eum dolorem ratione aliquid laboriosam inventore itaque deleniti suscipit. Inventore modi ratione nulla eveniet, quas praesentium ad, iste, accusantium natus tempora ea culpa. Excepturi architecto nemo possimus cupiditate animi!</span></p>
        <p><span>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nulla molestias nihil quas officia quaerat laudantium sed quae! Perferendis quidem magnam aut corrupti. Esse expedita optio unde natus quam reprehenderit nesciunt!</span><span>Iure tempora beatae consequatur adipisci magnam quia, fugiat reprehenderit, debitis eos maxime repellat tempore, optio doloribus nulla perferendis distinctio. Modi fuga distinctio, animi eum eius esse perspiciatis non perferendis a?</span><span>Repellendus quod ullam dolores, repudiandae maiores libero voluptates quas architecto at, quae optio magnam nostrum accusamus animi dolor. Veritatis fugit repellendus officia perferendis consectetur saepe enim ab suscipit atque impedit.</span><span>Nesciunt id delectus atque cumque incidunt. Illo est voluptate praesentium, ullam reprehenderit esse facere ipsa dolor necessitatibus consectetur sunt asperiores, repellendus nobis illum et? Non reiciendis voluptas beatae consectetur tempora?</span><span>Voluptas cumque voluptatibus eos magnam nesciunt, vel officiis itaque ea quia nostrum dolorem hic enim labore atque quisquam provident nulla eius laboriosam officia voluptate natus sit sunt! A, error minima.</span></p>
        <p><span>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam molestias minus iste deserunt similique voluptas amet nostrum dolorem, reprehenderit quisquam tenetur placeat cumque adipisci cum! Qui reiciendis incidunt doloribus voluptas.</span><span>Dolores dignissimos nesciunt suscipit laboriosam nostrum consectetur iusto eveniet aut dolore doloremque! Cupiditate, soluta quia! Voluptas unde deleniti consequuntur libero dolorum aperiam reprehenderit ad corrupti maxime sit, totam nulla nihil.</span><span>Cumque dolorem, culpa dignissimos exercitationem soluta possimus illum itaque blanditiis aperiam! Dolorem, ad sequi! Dolorum itaque delectus, harum, dolores ipsa enim et aperiam excepturi, corporis obcaecati consectetur reiciendis exercitationem illum.</span><span>Expedita totam soluta nesciunt ut doloremque reprehenderit? Ab animi optio voluptatum officiis ex distinctio cumque deleniti labore maxime, officia recusandae atque rerum explicabo, ullam iusto deserunt nesciunt consequuntur. Fuga, saepe.</span><span>Nobis dolore consequatur deserunt minima assumenda voluptates debitis quia nemo. Asperiores cum recusandae accusantium laborum, reiciendis esse inventore vero nam quas consectetur amet cupiditate laudantium atque est dolorum error consequatur.</span></p>
        <p><span>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatem adipisci dignissimos eius natus aperiam sint nulla. Doloribus eum, sapiente dolorum laboriosam hic optio delectus voluptas! Dignissimos voluptatibus perferendis similique modi?</span><span>Veritatis at maxime, eum omnis quia error nobis nemo sed velit aliquam vel tenetur consectetur saepe? Delectus, omnis, aliquam eius molestiae in, magni quam earum quasi explicabo ad quae! Totam.</span><span>Officiis, iste, dignissimos, libero nisi quaerat neque voluptates rem velit illo ab quidem. Aliquid, voluptatem odit quae odio, aperiam itaque assumenda, rerum at quasi minima dicta eius saepe rem deserunt!</span><span>Deleniti dolore, quae totam eaque iusto porro velit, modi ab maiores non in! Enim impedit sit ut aspernatur, facilis qui facere tempora modi deleniti laborum aliquam repudiandae, voluptatem iste quod!</span><span>Reprehenderit commodi doloribus et nulla totam aliquam magni? Reprehenderit, omnis quidem sapiente saepe exercitationem illum magnam accusamus, quia dolore voluptatibus temporibus cum quo, hic sint excepturi voluptate? Obcaecati, iusto ipsum?</span></p>
        <p><span>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quae voluptatem quaerat enim ut consequatur vitae culpa quibusdam tenetur, reprehenderit aliquam maiores quia illo! Quisquam nam, fugit quaerat officiis eaque sapiente!</span><span>Expedita, architecto excepturi voluptate iure debitis doloremque, voluptas rem quasi recusandae minus necessitatibus suscipit quod perspiciatis sed non quidem numquam facere, repellat corrupti sunt velit provident aliquam nobis. Quis, veniam!</span><span>Tempora, quos? Distinctio reiciendis, doloremque dolor dolore, hic laudantium maiores quod accusamus voluptatum officia, amet sequi nesciunt rerum ducimus tempora dolorem laborum necessitatibus iusto aperiam quae id nulla voluptates! Quo!</span><span>Veniam accusamus blanditiis aperiam cum! Optio itaque error at vero esse magnam incidunt recusandae fuga, suscipit eos sit. Ducimus quaerat fuga repellat reprehenderit corporis labore, nobis tempora dolorem esse ipsa?</span><span>Enim vitae, mollitia ipsam totam officiis ad, nostrum eius, magni perferendis sint esse aperiam fugiat reiciendis ut! Rem accusantium quia voluptate inventore debitis nisi ullam, sunt, minus accusamus magnam nihil!</span></p>
        </div>


      </>
    )
  }
  
  export default AboutPage